### ISSUE TITLE
Permanently delete content from the server once the user presses the delete button.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#285] opened 2019-10-06 00:36 UTC
As of right now, "deleting" content on Lemmy only hides it from public view (in most cases it is replaced with a generic "deleted" message). The data is still stored on the server. In the spirit of privacy and data protection, “real” content deletion should be implemented. I'm not sure how the uploaded files (images) of deleted posts are managed, but those should be also be deleted once the post is deleted.

Some discussion has taken place on the development instance: https://dev.lemmy.ml/post/28990/comment/532

**Comment by dessalines** [comment] 2019-10-06 01:47
This is also kind of a duplicate of #58

**Closed** 2019-10-15 23:50 UTC
Labels: enhancement
