### ISSUE TITLE
Auto fetch post title

### ISSUE THREAD

**Issue by freshy969** [dessalines/lemmy#125] opened 2019-04-26 18:03 UTC
Hello, I am suggesting that you add auto-fetch post title, 

Also a better permalink that will show the post title on the browser

**Comment by mister-monster** [comment] 2019-04-26 20:24
Duplicate of issue #112 ?

**Comment by dessalines** [comment] 2019-04-26 20:43
@freshy969 What does auto-fetch post title mean? You mean for url links for posts?

**Closed** 2019-04-30 14:04 UTC
Labels: question
