### ISSUE TITLE
Private communities

### ISSUE THREAD

**Issue by ivucica** [dessalines/lemmy#612] opened 2020-03-29 22:39 UTC
Besides the ability to restrict creation of new communities  https://github.com/dessalines/lemmy/issues/236, it would be useful to 

- restrict joining into existing communities
- restrict visibility of a community to members only

I'd like to set up a some communities that would not be crawlable by web indexers, or visible to users without logging in. These individual communities and posts made into them also shouldn't federate outside this Lemmy instance.

**Comment by dessalines** [comment] 2020-03-30 02:08
This is a dupe of #187

**Closed by dessalines** 2020-03-30 02:08 UTC
Labels: enhancement
